CREATE TABLE ENDERECO(
					  IDEND SERIAL PRIMARY KEY,
					  RUA VARCHAR(50) NOT NULL,
					  NUMERO INT NOT NULL,
					  BAIRRO VARCHAR(50) NOT NULL,
					  CEP VARCHAR(8) NOT NULL,
					  CIDADE VARCHAR(50) NOT NULL,
					  ESTADO CHAR(2) NOT NULL CHECK (ESTADO IN (
					    'AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO',
					    'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR',
					    'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO'
)));

CREATE TABLE DADOSPESSOAIS (
				 	  IDDADOS SERIAL PRIMARY KEY,
					  IDEND INT,
					  NOME VARCHAR(50) NOT NULL,
					  CPF VARCHAR(11) NOT NULL UNIQUE,
					  IDADE INT NOT NULL CHECK(IDADE > 0),
					  SEXO CHAR NOT NULL,
					  DATANASC TIMESTAMP NOT NULL,
					  TELEFONE VARCHAR (50) NOT NULL,
					  EMAIL VARCHAR(50) NOT NULL,
					  FOREIGN KEY (IDEND) REFERENCES ENDERECO(IDEND)
);

CREATE TABLE FUNCIONARIOS (
					  IDFUNC SERIAL PRIMARY KEY,
					  IDDADOS INT REFERENCES DADOSPESSOAIS(IDDADOS),
					  DATACONTR TIMESTAMP NOT NULL,
					  SALARIO NUMERIC(10,2) NOT NULL CHECK (SALARIO > 0),
					  FUNCAO VARCHAR(40) NOT NULL
);

CREATE TABLE MEDICOS (
					  IDMED SERIAL PRIMARY KEY,
					  IDDADOS INT REFERENCES DADOSPESSOAIS(IDDADOS),
					  CRM VARCHAR(20) NOT NULL UNIQUE,
					  ESPECIALIDADE VARCHAR(40) NOT NULL,
					  VALORCONS NUMERIC (6,2) NOT NULL CHECK (VALORCONS > 0),
					  NUMCONS INT NOT NULL CHECK (NUMCONS > 0),
					  DATACONTR TIMESTAMP NOT NULL
);

CREATE TABLE PACIENTES (
						IDPAC SERIAL PRIMARY KEY,
						IDDADOS INT REFERENCES DADOSPESSOAIS(IDDADOS)	
);

CREATE TABLE CONSULTAS(
						IDCONS SERIAL PRIMARY KEY,
						IDPAC INT REFERENCES PACIENTES(IDPAC),
						IDMED INT REFERENCES MEDICOS(IDMED),
						DATACONST TIMESTAMP NOT NULL,
						STATUS VARCHAR(40) CHECK (STATUS IN ('Agendada','Cancelada','Realizada'))
);

CREATE TABLE LOGIN(
				   USUARIO VARCHAR(50) PRIMARY KEY,
				   SENHA VARCHAR(50) NOT NULL
);