/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visao;

/**
 *
 * @author Mateus
 */
public class TelaAtualizarPacienteV extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAtualizarPacienteV2
     */
    public TelaAtualizarPacienteV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTEmail1 = new javax.swing.JTextField();
        jLTitulo1 = new javax.swing.JLabel();
        jTCidade1 = new javax.swing.JTextField();
        jLIDBusca1 = new javax.swing.JLabel();
        jLEstados1 = new javax.swing.JLabel();
        jTIDBusca1 = new javax.swing.JTextField();
        jCBEstados1 = new javax.swing.JComboBox<>();
        jLDadosPessoais1 = new javax.swing.JLabel();
        jLNome1 = new javax.swing.JLabel();
        jLIdade1 = new javax.swing.JLabel();
        jTNome1 = new javax.swing.JTextField();
        jLCPF1 = new javax.swing.JLabel();
        jTIdade1 = new javax.swing.JTextField();
        jTCPF1 = new javax.swing.JTextField();
        jLEndereco1 = new javax.swing.JLabel();
        jLSexo1 = new javax.swing.JLabel();
        jTSexo1 = new javax.swing.JTextField();
        jLDataNasc1 = new javax.swing.JLabel();
        jTDataNasc1 = new javax.swing.JTextField();
        jTCEP1 = new javax.swing.JTextField();
        jLTel1 = new javax.swing.JLabel();
        jLRua1 = new javax.swing.JLabel();
        jBAtualizar1 = new javax.swing.JButton();
        jTRua1 = new javax.swing.JTextField();
        jTTel1 = new javax.swing.JTextField();
        jLNum1 = new javax.swing.JLabel();
        jLEmail1 = new javax.swing.JLabel();
        jLCEP1 = new javax.swing.JLabel();
        jTNum1 = new javax.swing.JTextField();
        jLCidade1 = new javax.swing.JLabel();

        jLTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLTitulo1.setText("Atualizar Paciente");

        jLIDBusca1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLIDBusca1.setText("ID do Paciente:");

        jLEstados1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLEstados1.setText("Estado:");

        jCBEstados1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC  ", "AL  ", "AM  ", "AP  ", "BA  ", "CE  ", "DF  ", "ES  ", "GO  ", "MA  ", "MG  ", "MS  ", "MT  ", "PA  ", "PB  ", "PE  ", "PI  ", "PR  ", "RJ  ", "RN  ", "RO  ", "RR  ", "RS  ", "SC  ", "SE  ", "SP  ", "TO" }));

        jLDadosPessoais1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLDadosPessoais1.setText("Dados Pessoais");

        jLNome1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLNome1.setText("Nome:");

        jLIdade1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLIdade1.setText("Idade:");

        jLCPF1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLCPF1.setText("CPF:");

        jLEndereco1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLEndereco1.setText("Endereço");

        jLSexo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLSexo1.setText("Sexo:");

        jLDataNasc1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLDataNasc1.setText("Data de Nascimento:");

        jLTel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLTel1.setText("Telefone:");

        jLRua1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLRua1.setText("Rua:");

        jBAtualizar1.setText("Atualizar");
        jBAtualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizar1ActionPerformed(evt);
            }
        });

        jLNum1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLNum1.setText("Nº:");

        jLEmail1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLEmail1.setText("Email:");

        jLCEP1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLCEP1.setText("CEP:");

        jLCidade1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLCidade1.setText("Cidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCPF1)
                            .addComponent(jLNome1)
                            .addComponent(jLIdade1)
                            .addComponent(jLSexo1)
                            .addComponent(jLDataNasc1)
                            .addComponent(jLTel1)
                            .addComponent(jLEmail1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTSexo1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTDataNasc1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTTel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTEmail1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCPF1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTIdade1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNome1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLDadosPessoais1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLIDBusca1)
                        .addGap(18, 18, 18)
                        .addComponent(jTIDBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLTitulo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLEndereco1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCEP1)
                        .addGap(30, 30, 30)
                        .addComponent(jTCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLRua1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLCidade1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLNum1)
                                .addGap(38, 38, 38)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTRua1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLEstados1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBEstados1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBAtualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLTitulo1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIDBusca1)
                    .addComponent(jTIDBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLEndereco1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCEP1)
                            .addComponent(jTCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLRua1)
                            .addComponent(jTRua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNum1)
                            .addComponent(jTNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCidade1)
                            .addComponent(jTCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEstados1)
                            .addComponent(jCBEstados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLDadosPessoais1)
                            .addGap(238, 238, 238))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLNome1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTNome1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLCPF1)
                                .addComponent(jTCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLIdade1)
                                .addComponent(jTIdade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLSexo1)
                                .addComponent(jTSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLDataNasc1)
                                .addComponent(jTDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLTel1)
                                .addComponent(jTTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLEmail1)
                                .addComponent(jTEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBAtualizar1)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAtualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAtualizar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar1;
    private javax.swing.JComboBox<String> jCBEstados1;
    private javax.swing.JLabel jLCEP1;
    private javax.swing.JLabel jLCPF1;
    private javax.swing.JLabel jLCidade1;
    private javax.swing.JLabel jLDadosPessoais1;
    private javax.swing.JLabel jLDataNasc1;
    private javax.swing.JLabel jLEmail1;
    private javax.swing.JLabel jLEndereco1;
    private javax.swing.JLabel jLEstados1;
    private javax.swing.JLabel jLIDBusca1;
    private javax.swing.JLabel jLIdade1;
    private javax.swing.JLabel jLNome1;
    private javax.swing.JLabel jLNum1;
    private javax.swing.JLabel jLRua1;
    private javax.swing.JLabel jLSexo1;
    private javax.swing.JLabel jLTel1;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JTextField jTCEP1;
    private javax.swing.JTextField jTCPF1;
    private javax.swing.JTextField jTCidade1;
    private javax.swing.JTextField jTDataNasc1;
    private javax.swing.JTextField jTEmail1;
    private javax.swing.JTextField jTIDBusca1;
    private javax.swing.JTextField jTIdade1;
    private javax.swing.JTextField jTNome1;
    private javax.swing.JTextField jTNum1;
    private javax.swing.JTextField jTRua1;
    private javax.swing.JTextField jTSexo1;
    private javax.swing.JTextField jTTel1;
    // End of variables declaration//GEN-END:variables
}
