/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visao;

/**
 *
 * @author Gabriel Danieli
 */
public class TelaBuscaFuncionarioV extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaBuscarFuncionarioV
     */
    public TelaBuscaFuncionarioV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTIDRemove = new javax.swing.JTextField();
        jLTitulo = new javax.swing.JLabel();
        jLIDBusca = new javax.swing.JLabel();
        jBIDDadosEmpresa = new javax.swing.JButton();
        jBIDDadosPessoais = new javax.swing.JButton();
        jBIDEndereco = new javax.swing.JButton();
        jBBuscaTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLTitulo.setText("Buscar Funcionário");

        jLIDBusca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLIDBusca.setText("ID do Funcionário:");

        jBIDDadosEmpresa.setText("Dados Empresa");
        jBIDDadosEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIDDadosEmpresaActionPerformed(evt);
            }
        });

        jBIDDadosPessoais.setText("Dados Pessoais");
        jBIDDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIDDadosPessoaisActionPerformed(evt);
            }
        });

        jBIDEndereco.setText("Endereço");
        jBIDEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIDEnderecoActionPerformed(evt);
            }
        });

        jBBuscaTodos.setText("Todos Funcionários");
        jBBuscaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscaTodosActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLIDBusca)
                        .addGap(18, 18, 18)
                        .addComponent(jTIDRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBIDDadosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBBuscaTodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBIDDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBIDEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIDBusca)
                    .addComponent(jTIDRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBIDDadosPessoais)
                    .addComponent(jBIDEndereco)
                    .addComponent(jBIDDadosEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBBuscaTodos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIDDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIDDadosPessoaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBIDDadosPessoaisActionPerformed

    private void jBIDEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIDEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBIDEnderecoActionPerformed

    private void jBIDDadosEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIDDadosEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBIDDadosEmpresaActionPerformed

    private void jBBuscaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscaTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBuscaTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscaTodos;
    private javax.swing.JButton jBIDDadosEmpresa;
    private javax.swing.JButton jBIDDadosPessoais;
    private javax.swing.JButton jBIDEndereco;
    private javax.swing.JLabel jLIDBusca;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTIDRemove;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
